apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: beo57gbcg-go 
  janus-idp.io/tekton: beo57gbcg-go
  backstage.io/kubernetes-id: beo57gbcg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: beo57gbcg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml